### PR TITLE
Arty a7

### PR DESCRIPTION
**Pull request by bl0x**
This produces a bitfile that fits into the FPGA of a Digilent Arty A7 35 board including the DRAM core.
Some resources needed to be reduced compared to the basys version.

### CODE REVIEW

**Comment by olofk** [comment]
Fantastic! Thanks for this. I hope to get a chance to review next week, but if you haven't heard back, please remind me. Got a fair amount of PRs to review so might miss it

**Comment by bl0x** [comment]
I now also tried to actually run the bitfile and it does so without any trouble!
I'm amazed! ... Connecting with openOCD as debugger works and I can toggle the LEDs.

**Comment by olofk** [comment]
Fantastic! Thanks for this. Looks perfectly fine to me. Will give it a try once I'm back at the office. Picked and pushed

**Comment by bl0x** [comment]
yay =) thx @olofk

**Pull request merged**
