### PR TITLE
Updated OpenOCD .cfg files for proper ICACHE flush

### PR DESCRIPTION
**Pull request by JanMatCodasip**

### CODE REVIEW

**Comment by JanMatCodasip** [comment]
@olofk - Hi Olof,

I noticed that in SweRVolf 0.7, ICACHE is enabled by default. Actually, to make the ICACHE work with OpenOCD, two more things need to be done:

1) A very recent OpenOCD version has to be used that has support for "step-start" event.

- This change is in the official OpenOCD upstream but not yet in `riscv-openocd` fork, mentioned in the SweRVolf's README. 
- I have [submitted](https://github.com/riscv/riscv-openocd/pull/481) this single feature to `riscv-openocd`, too. Once accepted, this will be no longer an issue and the user can freely choose whether to take OpenOCD from the upstream or the RISC-V fork.

2) OpenOCD needs to be configured to flush the SweRV's Icache. 

- Please find the needed changes in .cfg files in this pull request.

Feel free to reach back if anything.

Regards, 
Jan

**Comment by olofk** [comment]
Thanks @JanMatCodasip! I had completely missed this one. Pulling it in now.

**Comment by JanMatCodasip** [comment]
> I had completely missed this one. Pulling it in now.

Thank you, no problem. 

Once SweRV 1.8 is adopted, I expect one more change to the OpenOCD configuration files. Namely: `riscv set_mem_access abstract` so that OpenOCD can access all memory, including the core-local ones.

**Comment by olofk** [comment]
Aha. Good to know. Can you please add that as a patch as well? I'm just about to release a new SweRVolf with 1.8, so it would be great to add this change as well before the release

**Comment by JanMatCodasip** [comment]
> Can you please add that as a patch as well? I'm just about to release a new SweRVolf with 1.8

Of course. Here you are: https://github.com/chipsalliance/Cores-SweRVolf/pull/23

**Pull request merged**
